services:
  # ZION Seed Node 1 (Primary Bootstrap Daemon)
  seed1:
    image: zion:bootstrap-fixed
    container_name: zion-seed1
    ports:
      - "18080:18080"  # P2P port
      - "18081:18081"  # RPC port
    environment:
      - ZION_P2P_BIND_PORT=18080
      - ZION_RPC_BIND_PORT=18081
      - ZION_LOG_LEVEL=1
    volumes:
      - zion-seed1-data:/root/.zion
    networks:
      - zion-seeds
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18081/getheight"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ZION Seed Node 2 (Backup CryptoNote Daemon)  
  zion-seed2:
    image: zion:production-fixed
    container_name: zion-seed2
    ports:
      - "28080:18080"  # P2P port (different external)
      - "28081:18081"  # RPC port (different external)
    environment:
      - ZION_P2P_BIND_PORT=18080
      - ZION_RPC_BIND_PORT=18081
      - ZION_LOG_LEVEL=1
      - ZION_SEED_NODES=zion-seed1:18080
    volumes:
      - zion-seed2-data:/root/.zion
    networks:
      - zion-seeds
    restart: unless-stopped
    depends_on:
      - zion-seed1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18081/getheight"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # RPC Shim (connects to seed nodes)
  zion-rpc-shim:
    build:
      context: ./adapters/zion-rpc-shim
      dockerfile: Dockerfile
    container_name: zion-rpc-shim
    ports:
      - "18089:18089"
    environment:
      - RPC_PORT=18089
      - ZION_RPC_URLS=http://zion-seed1:18081/json_rpc,http://zion-seed2:18081/json_rpc
    depends_on:
      - zion-seed1
      - zion-seed2
    networks:
      - zion-seeds
    restart: unless-stopped

  # Mining Pool (connects via RPC shim)
  zion-mining-pool:
    build:
      context: ./pool
      dockerfile: Dockerfile
    container_name: zion-mining-pool
    ports:
      - "3333:3333"
    environment:
      - POOL_PORT=3333
      - POOL_BIND=0.0.0.0
      - RPC_HOST=zion-rpc-shim
      - RPC_PORT=18089
    depends_on:
      - zion-rpc-shim
    networks:
      - zion-seeds
    restart: unless-stopped

  # Wallet Adapter
  zion-wallet-adapter:
    build:
      context: ./adapters/wallet-adapter
      dockerfile: Dockerfile
    container_name: zion-wallet-adapter
    ports:
      - "18099:18099"
    environment:
      - ADAPTER_PORT=18099
      - RPC_HOST=zion-rpc-shim
      - RPC_PORT=18089
    depends_on:
      - zion-rpc-shim
    networks:
      - zion-seeds
    restart: unless-stopped

volumes:
  zion-seed1-data:
  zion-seed2-data:

networks:
  zion-seeds:
    driver: bridge