version: '3.8'
services:
  legacy-daemon:
    build:
      context: ../legacy/experiments/zion-cryptonote
      dockerfile: ../../../../docker/Dockerfile.zion-cryptonote.minimal
    container_name: legacy-daemon
    ports:
      - "18081:18081"
    environment:
      - CXXFLAGS=-O2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:18081/json_rpc"]
      interval: 30s
      timeout: 5s
      retries: 5
  core:
    image: zion-core-full
    container_name: zion-core
    env_file:
      - .env
    ports:
      - "${PORT:-8602}:8601"      # Používám 8602 kvůli SSH server konfliktu
      - "${STRATUM_PORT:-3334}:3333"  # Používám 3334 kvůli SSH server konfliktu  
    environment:
      - PORT=8601
      - STRATUM_PORT=3333
      - INITIAL_DIFFICULTY=1000
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.frontend
    container_name: zion-frontend
    depends_on:
      - core
      - legacy-daemon
    ports:
      - "3000:3000"
    restart: unless-stopped
  miner:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.miner
    container_name: zion-miner
    depends_on:
      - core
      - legacy-daemon
    restart: unless-stopped
    entrypoint: ["/app/zion-miner"]
