global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['zion-alertmanager:9093']

scrape_configs:
  - job_name: 'zion-shim-direct'
    static_configs:
      - targets: ['zion-rpc-shim:18089']
    metrics_path: /metrics

  - job_name: 'zion-shim-proxy'
    static_configs:
      - targets: ['zion-proxy:8080']
    metrics_path: /shim/metrics

  - job_name: 'zion-adapter-proxy'
    static_configs:
      - targets: ['zion-proxy:8080']
    metrics_path: /adapter/metrics
