services:
  zion-node:
    build:
      context: ..
      dockerfile: docker/Dockerfile.zion-cryptonote
    image: zion-cryptonote:latest
    container_name: zion-node
    ports:
      - "18080:18080" # P2P
      - "18081:18081" # RPC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-lc", "pgrep -x ziond >/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - zion_data:/var/lib/zion
    command: ["/usr/local/bin/ziond", "--data-dir", "/var/lib/zion", "--p2p-bind-port", "18080", "--rpc-bind-port", "18081"]

volumes:
  zion_data:
