version: "3.8"

services:
  # ZION Core (TypeScript) - replaces JavaScript UZI pool
  zion-core:
    build:
      context: ..
      dockerfile: docker/Dockerfile.zion-core
    image: zion:core-typescript
    container_name: zion-core-prod
    restart: unless-stopped
    environment:
      - ZION_MODE=pool
      - ZION_LOG_LEVEL=debug
      - ZION_POOL_ADDRESS=Z3222ywic7fGUZHv9EfFwEKf1VJRrEqPbLrHgRiBb43LWaS1Cz2gVwgdF2kvUPsGb9jSvUUf31oNCSZgNEtUiGDT4sBLtXmGzc
      - RPC_HOST=rpc-shim
      - RPC_PORT=18089
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    ports:
      - "3333:3333"     # Mining pool port
      - "3000:3000"     # API/WebUI port
      - "8080:8080"     # WebSocket port (optional)
    depends_on:
      redis:
        condition: service_healthy
      rpc-shim:
        condition: service_healthy
    networks:
      - zion-seeds
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  zion-seeds:
    external: true
