services:
  prometheus:
    image: prom/prometheus:latest
    container_name: zion-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prom-data:/prometheus
    networks:
      - zion-seeds
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--web.enable-lifecycle",
      "--storage.tsdb.retention.time=7d",
      "--storage.tsdb.path=/prometheus",
      "--alertmanager.notification-queue-capacity=10000",
      "--query.lookback-delta=1m"
    ]

  alertmanager:
    image: prom/alertmanager:latest
    container_name: zion-alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    networks:
      - zion-seeds

  grafana:
    image: grafana/grafana:latest
    container_name: zion-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - zion-seeds
    depends_on:
      - prometheus

networks:
  zion-seeds:
    external: true

volumes:
  prom-data:
  grafana-data:
